ALTER TABLE payments ADD COLUMN tendered DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN change DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN discount DOUBLE NOT NULL DEFAULT 0;
