-- Your SQL goes here
CREATE TABLE IF NOT EXISTS order_details (
  id UNSIGNED INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uuid TEXT NOT NULL UNIQUE,
  product_id UNSIGNED INTEGER NOT NULL,
  order_id UNSIGNED INTEGER NOT NULL,
  quantity REAL NOT NULL,
  price REAL NOT NULL,

  FOREIGN KEY(product_id) REFERENCES products(id),
  FOREIGN KEY(order_id) REFERENCES orders(id),
);
